# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjectIIGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(995, 813)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.949, x2:1, y2:0, stop:0.0995025 rgba(82, 120, 145, 255), stop:0.985075 rgba(61, 71, 91, 255));\n"
"border-radius: 20px;")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Title_Bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.Title_Bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Title_Bar.setStyleSheet("background-color: none")
        self.Title_Bar.setFrameShape(QtWidgets.QFrame.Box)
        self.Title_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Title_Bar.setObjectName("Title_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Title_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.Title_Bar)
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setStyleSheet("color: rgb(177, 197, 212);")
        self.frame_title.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_3.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight SemiConde")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.verticalLayout_3.addWidget(self.label_title)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.Title_Bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.btn_maximize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_maximize.setGeometry(QtCore.QRect(10, 20, 16, 16))
        self.btn_maximize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_maximize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_maximize.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 8px; \n"
"    background-color: rgb(85, 255, 127);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(85, 255, 127, 150);\n"
"\n"
"}\n"
"")
        self.btn_maximize.setText("")
        self.btn_maximize.setObjectName("btn_maximize")
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setGeometry(QtCore.QRect(70, 20, 16, 16))
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 8px; \n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 0, 0, 150);\n"
"\n"
"}\n"
"")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setGeometry(QtCore.QRect(40, 20, 16, 16))
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 8px; \n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 170, 0, 150);\n"
"\n"
"}\n"
"")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout_2.addWidget(self.Title_Bar)
        self.Content_Bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.Content_Bar.setStyleSheet("")
        self.Content_Bar.setFrameShape(QtWidgets.QFrame.Panel)
        self.Content_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content_Bar.setObjectName("Content_Bar")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Content_Bar)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 981, 711))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1001, 711))
        self.frame.setStyleSheet("background-color: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 70, 891, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"color: rgb(216, 185, 170);\n"
"\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.next_btn1 = QtWidgets.QPushButton(self.frame)
        self.next_btn1.setGeometry(QtCore.QRect(580, 380, 150, 75))
        self.next_btn1.setMinimumSize(QtCore.QSize(150, 75))
        self.next_btn1.setMaximumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        self.next_btn1.setFont(font)
        self.next_btn1.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 20px; \n"
"    \n"
"    \n"
"    background-color: rgb(65, 79, 100);\n"
"    color: rgb(177, 197, 212);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 8px solid rgba(65, 79, 100,150);\n"
"}\n"
"")
        self.next_btn1.setObjectName("next_btn1")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(140, 250, 711, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(186, 207, 222);\n"
"background-color: rgb(158, 176, 189);\n"
"color: rgb(213, 238, 255);\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"}\n"
"QLineEdit:hover {\n"
" border: 2px solid rgb(213, 238, 255);\n"
"}\n"
"QLineEdit:focus{\n"
" border: 2px solid rgb(213, 238, 255);\n"
"background-color: rgb(158, 176, 189);\n"
"}\n"
"\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.btn_uploadimg = QtWidgets.QPushButton(self.frame)
        self.btn_uploadimg.setGeometry(QtCore.QRect(270, 380, 150, 75))
        self.btn_uploadimg.setMinimumSize(QtCore.QSize(150, 75))
        self.btn_uploadimg.setMaximumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        self.btn_uploadimg.setFont(font)
        self.btn_uploadimg.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 20px; \n"
"    \n"
"    \n"
"    background-color: rgb(65, 79, 100);\n"
"    color: rgb(177, 197, 212);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 8px solid rgba(65, 79, 100,150);\n"
"}\n"
"")
        self.btn_uploadimg.setObjectName("btn_uploadimg")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 981, 721))
        self.frame_2.setStyleSheet("background-color:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.next_btn1_2 = QtWidgets.QPushButton(self.frame_2)
        self.next_btn1_2.setGeometry(QtCore.QRect(800, 620, 150, 75))
        self.next_btn1_2.setMinimumSize(QtCore.QSize(150, 75))
        self.next_btn1_2.setMaximumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        self.next_btn1_2.setFont(font)
        self.next_btn1_2.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 20px; \n"
"    \n"
"    \n"
"    background-color: rgb(65, 79, 100);\n"
"    color: rgb(177, 197, 212);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 8px solid rgba(65, 79, 100,150);\n"
"}\n"
"")
        self.next_btn1_2.setObjectName("next_btn1_2")
        self.next_btn1_3 = QtWidgets.QPushButton(self.frame_2)
        self.next_btn1_3.setGeometry(QtCore.QRect(630, 620, 150, 75))
        self.next_btn1_3.setMinimumSize(QtCore.QSize(150, 75))
        self.next_btn1_3.setMaximumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        self.next_btn1_3.setFont(font)
        self.next_btn1_3.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 20px; \n"
"    \n"
"    \n"
"    background-color: rgb(65, 79, 100);\n"
"    color: rgb(177, 197, 212);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 8px solid rgba(65, 79, 100,150);\n"
"}\n"
"")
        self.next_btn1_3.setObjectName("next_btn1_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 561, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(216, 185, 170);")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(20, 140, 561, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(216, 185, 170);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(20, 270, 561, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(216, 185, 170);")
        self.label_8.setObjectName("label_8")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_2.setGeometry(QtCore.QRect(50, 340, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color: rgb(177, 197, 212);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.checkBox = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox.setGeometry(QtCore.QRect(80, 390, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_2.setGeometry(QtCore.QRect(330, 430, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_3.setGeometry(QtCore.QRect(80, 470, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_4.setGeometry(QtCore.QRect(80, 430, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_5.setGeometry(QtCore.QRect(330, 390, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_6.setGeometry(QtCore.QRect(330, 510, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_8.setGeometry(QtCore.QRect(330, 470, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_9.setGeometry(QtCore.QRect(80, 510, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_9.setObjectName("checkBox_9")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(580, 30, 381, 311))
        self.label_9.setStyleSheet("")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.next_btn1_6 = QtWidgets.QPushButton(self.frame_2)
        self.next_btn1_6.setGeometry(QtCore.QRect(460, 620, 150, 75))
        self.next_btn1_6.setMinimumSize(QtCore.QSize(150, 75))
        self.next_btn1_6.setMaximumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        self.next_btn1_6.setFont(font)
        self.next_btn1_6.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 20px; \n"
"    \n"
"    \n"
"    background-color: rgb(65, 79, 100);\n"
"    color: rgb(177, 197, 212);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 8px solid rgba(65, 79, 100,150);\n"
"}\n"
"")
        self.next_btn1_6.setObjectName("next_btn1_6")
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setGeometry(QtCore.QRect(70, 90, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox{\n"
"border: 2px solid rgb(186, 207, 222);\n"
"background-color: rgb(158, 176, 189);\n"
"color: rgb(255, 255, 255);\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"}\n"
"QComboBox:hover {\n"
" border: 2px solid rgb(213, 238, 255);\n"
"}\n"
"QComboBox:focus{\n"
" border: 2px solid rgb(213, 238, 255);\n"
"background-color: rgb(158, 176, 189);\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(230, 210, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(158, 176, 189);")
        self.label_15.setObjectName("label_15")
        self.horizontalSlider = QtWidgets.QSlider(self.frame_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(50, 250, 381, 22))
        self.horizontalSlider.setMinimum(10)
        self.horizontalSlider.setMaximum(5000)
        self.horizontalSlider.setSingleStep(10)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.frame_3 = QtWidgets.QFrame(self.page_3)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 981, 711))
        self.frame_3.setStyleSheet("background-color:none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(580, 30, 381, 311))
        self.label_6.setStyleSheet("")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.next_btn1_4 = QtWidgets.QPushButton(self.frame_3)
        self.next_btn1_4.setGeometry(QtCore.QRect(810, 620, 150, 75))
        self.next_btn1_4.setMinimumSize(QtCore.QSize(150, 75))
        self.next_btn1_4.setMaximumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        self.next_btn1_4.setFont(font)
        self.next_btn1_4.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 20px; \n"
"    \n"
"    \n"
"    background-color: rgb(65, 79, 100);\n"
"    color: rgb(177, 197, 212);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 8px solid rgba(65, 79, 100,150);\n"
"}\n"
"")
        self.next_btn1_4.setObjectName("next_btn1_4")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 561, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(216, 185, 170);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(50, 80, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(160, 197, 212);")
        self.label_11.setObjectName("label_11")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_4.setGeometry(QtCore.QRect(60, 120, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_5.setGeometry(QtCore.QRect(60, 200, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_6.setGeometry(QtCore.QRect(60, 240, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_7.setGeometry(QtCore.QRect(60, 270, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_7.setFont(font)
        self.radioButton_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_7.setObjectName("radioButton_7")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(50, 330, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(160, 197, 212);")
        self.label_12.setObjectName("label_12")
        self.checkBox_11 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_11.setGeometry(QtCore.QRect(70, 430, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_12 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_12.setGeometry(QtCore.QRect(70, 470, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_13 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_13.setGeometry(QtCore.QRect(70, 510, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_13.setObjectName("checkBox_13")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(60, 550, 561, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(216, 185, 170);")
        self.label_14.setObjectName("label_14")
        self.radioButton_8 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_8.setGeometry(QtCore.QRect(70, 600, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_8.setFont(font)
        self.radioButton_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.radioButton_8.setObjectName("radioButton_8")
        self.next_btn1_7 = QtWidgets.QPushButton(self.frame_3)
        self.next_btn1_7.setGeometry(QtCore.QRect(640, 620, 150, 75))
        self.next_btn1_7.setMinimumSize(QtCore.QSize(150, 75))
        self.next_btn1_7.setMaximumSize(QtCore.QSize(150, 75))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        self.next_btn1_7.setFont(font)
        self.next_btn1_7.setStyleSheet("QPushButton {\n"
"border: none;\n"
"border-radius: 20px; \n"
"    \n"
"    \n"
"    background-color: rgb(65, 79, 100);\n"
"    color: rgb(177, 197, 212);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"border: 8px solid rgba(65, 79, 100,150);\n"
"}\n"
"")
        self.next_btn1_7.setObjectName("next_btn1_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 160, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"border: 2px solid rgb(186, 207, 222);\n"
"background-color: rgb(158, 176, 189);\n"
"color: rgb(213, 238, 255);\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"}\n"
"QLineEdit:hover {\n"
" border: 2px solid rgb(213, 238, 255);\n"
"}\n"
"QLineEdit:focus{\n"
" border: 2px solid rgb(213, 238, 255);\n"
"background-color: rgb(158, 176, 189);\n"
"}\n"
"\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.checkBox_14 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_14.setGeometry(QtCore.QRect(360, 430, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_15 = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_15.setGeometry(QtCore.QRect(360, 470, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.checkBox_15.setObjectName("checkBox_15")
        self.radioButton = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton.setGeometry(QtCore.QRect(60, 380, 511, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color: rgb(216, 185, 170);")
        self.radioButton.setObjectName("radioButton")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.frame_4 = QtWidgets.QFrame(self.page_4)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 981, 711))
        self.frame_4.setStyleSheet("background-color:none;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.InputImg_label = QtWidgets.QLabel(self.frame_4)
        self.InputImg_label.setGeometry(QtCore.QRect(340, 40, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(10)
        self.InputImg_label.setFont(font)
        self.InputImg_label.setStyleSheet("background-color: rgb(104, 101, 115);\n"
"border: 2px solid rgb(177, 197, 212);\n"
"color: rgb(177, 197, 212);")
        self.InputImg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.InputImg_label.setObjectName("InputImg_label")
        self.label_5 = QtWidgets.QLabel(self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(340, 110, 381, 311))
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(30, 460, 521, 161))
        self.frame_5.setStyleSheet("background-color: none;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.Prediction_label = QtWidgets.QLabel(self.frame_5)
        self.Prediction_label.setGeometry(QtCore.QRect(20, 100, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(12)
        self.Prediction_label.setFont(font)
        self.Prediction_label.setStyleSheet("color: rgb(216, 185, 170);")
        self.Prediction_label.setObjectName("Prediction_label")
        self.results_label = QtWidgets.QLabel(self.frame_5)
        self.results_label.setGeometry(QtCore.QRect(10, 5, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.results_label.setFont(font)
        self.results_label.setStyleSheet("color: rgb(216, 185, 170);\n"
"border: 5px solid rgb(216, 185, 170);")
        self.results_label.setObjectName("results_label")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(110, 100, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(216, 185, 170);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_5)
        self.label_3.setGeometry(QtCore.QRect(170, 170, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(216, 185, 170);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(400, 110, 571, 491))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(177, 197, 212);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.frame_6 = QtWidgets.QFrame(self.page_5)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 971, 711))
        self.frame_6.setStyleSheet("background-color: none;\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(30, 110, 911, 561))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color: none;\n"
"color: rgb(216, 185, 170);\n"
"")
        self.label_17.setText("")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_13 = QtWidgets.QLabel(self.frame_6)
        self.label_13.setGeometry(QtCore.QRect(30, 10, 561, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(216, 185, 170);")
        self.label_13.setObjectName("label_13")
        self.stackedWidget.addWidget(self.page_5)
        self.verticalLayout_2.addWidget(self.Content_Bar)
        self.Credits_Bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.Credits_Bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Credits_Bar.setStyleSheet("background-color: none")
        self.Credits_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Credits_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Credits_Bar.setObjectName("Credits_Bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Credits_Bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_label_credits = QtWidgets.QFrame(self.Credits_Bar)
        self.frame_label_credits.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_credits.setObjectName("frame_label_credits")
        self.label_credits = QtWidgets.QLabel(self.frame_label_credits)
        self.label_credits.setGeometry(QtCore.QRect(20, 0, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiLight Condensed")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_credits.setFont(font)
        self.label_credits.setStyleSheet("color: rgb(177, 197, 212);")
        self.label_credits.setObjectName("label_credits")
        self.horizontalLayout_2.addWidget(self.frame_label_credits)
        self.frame_grip = QtWidgets.QFrame(self.Credits_Bar)
        self.frame_grip.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_2.addWidget(self.frame_grip)
        self.verticalLayout_2.addWidget(self.Credits_Bar)
        self.verticalLayout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title.setText(_translate("MainWindow", "Age-Group Classifier"))
        self.btn_maximize.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.label.setText(_translate("MainWindow", "Welcome to the non-parametric age classifier!"))
        self.next_btn1.setText(_translate("MainWindow", "Next"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter an image location..."))
        self.btn_uploadimg.setText(_translate("MainWindow", "Upload Image"))
        self.next_btn1_2.setText(_translate("MainWindow", "Next"))
        self.next_btn1_3.setText(_translate("MainWindow", "Predict"))
        self.label_4.setText(_translate("MainWindow", "Choose the following pre-trained model:"))
        self.label_7.setText(_translate("MainWindow", "1. Choose the number of training data:"))
        self.label_8.setText(_translate("MainWindow", "2. Choose the features to be used in training:"))
        self.radioButton_2.setText(_translate("MainWindow", "Anthropometric Model"))
        self.checkBox.setText(_translate("MainWindow", "Facial Index"))
        self.checkBox_2.setText(_translate("MainWindow", "Nasal Index"))
        self.checkBox_3.setText(_translate("MainWindow", "Intercanthal Index"))
        self.checkBox_4.setText(_translate("MainWindow", "Mandibular Index"))
        self.checkBox_5.setText(_translate("MainWindow", "Eye Fissure Index"))
        self.checkBox_6.setText(_translate("MainWindow", "Mouth-Face Width Index"))
        self.checkBox_8.setText(_translate("MainWindow", "Vermilion Height Index"))
        self.checkBox_9.setText(_translate("MainWindow", "Orbital Width Index"))
        self.next_btn1_6.setText(_translate("MainWindow", "Back"))
        self.comboBox.setItemText(0, _translate("MainWindow", "K-Nearest Neighbor"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Decision Trees"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Support Vector Machines"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Convolutional Neural Network"))
        self.label_15.setText(_translate("MainWindow", "10"))
        self.next_btn1_4.setText(_translate("MainWindow", "Train"))
        self.label_10.setText(_translate("MainWindow", "3. Choose the agent(s) for training:"))
        self.label_11.setText(_translate("MainWindow", "Single Agent"))
        self.radioButton_4.setText(_translate("MainWindow", "K-Nearest Neighbor"))
        self.radioButton_5.setText(_translate("MainWindow", "Decision Trees"))
        self.radioButton_6.setText(_translate("MainWindow", "Support Vector Machines"))
        self.radioButton_7.setText(_translate("MainWindow", "Convolutional Neural Network"))
        self.label_12.setText(_translate("MainWindow", "Ensemble Methods"))
        self.checkBox_11.setText(_translate("MainWindow", "K-Nearest Neighbor"))
        self.checkBox_12.setText(_translate("MainWindow", "Decision Trees"))
        self.checkBox_13.setText(_translate("MainWindow", "Support Vector Machines"))
        self.label_14.setText(_translate("MainWindow", "Choose the following for an ensemble using Bagging:"))
        self.radioButton_8.setText(_translate("MainWindow", "Random Forest Classifier"))
        self.next_btn1_7.setText(_translate("MainWindow", "Back"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Enter the number of neighbors..."))
        self.checkBox_14.setText(_translate("MainWindow", "Linear Regression"))
        self.checkBox_15.setText(_translate("MainWindow", "Gaussian Naive Bayes"))
        self.radioButton.setText(_translate("MainWindow", "Choose the agent(s) for an ensemble using Stacking:"))
        self.InputImg_label.setText(_translate("MainWindow", "Input Image:"))
        self.Prediction_label.setText(_translate("MainWindow", "Prediction :"))
        self.results_label.setText(_translate("MainWindow", "Classifier Results :"))
        self.label_13.setText(_translate("MainWindow", "Model Metrics:"))
        self.label_credits.setText(_translate("MainWindow", "By : Rachelle Abdel Massih, Myriam Abou Atmeh, Sara Oud"))
        # Connect the 'Upload Image' button to the btn_oploadimg_handler function
        self.btn_uploadimg.clicked.connect(self.btn_uploadimg_handler)

    def btn_uploadimg_handler(self):
            # print("Button pressed")
            # Call the open_dialog_box function
            self.open_dialog_box()

    def open_dialog_box(self):
            # Open the file explorer on local disk and get the path of the selected image
            filename = QFileDialog.getOpenFileName()
            path = filename[0]
            print(path)
            # Display the selected path on the QLineEdit widget
            self.lineEdit.setText(str(path))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
